const cardData = [
  {
    name: "Zelda Screen 6",
    type: "long",
    background: "ZeldaScreen6.jpg",
    instructions: "ZeldaInst6.jpg",
    groups: [
      ["right", "right", "sword", "patras", "patras", "patras", "patras"],
      ["sword", "sword", "sword", "patras", "patras", "patras", "patras"],
    ],
    locations: [
      [
        11,
        22.6,
        30.4,
        33.4,
        31.5,
        30.3,
        20.7,
        76.1,
        67,
        57.9,
        59,
        60.6,
        68,
        77.5,
      ],
      [
        19,
        6.9,
        3,
        3.9,
        5.3,
        6.6,
        -0.1,
        -62.6,
        -71,
        -74.8,
        -72,
        -70.5,
        -73.4,
        -83.2,
      ],
    ],
  },
];
